# Generated by Django 5.2.4 on 2025-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
