# Generated by Django 5.2.4 on 2025-07-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0002_alter_training_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('tg_name', models.CharField(blank=True, unique=True, verbose_name='Ник telegram')),
                ('tg_id', models.CharField(blank=True, unique=True, verbose_name='Telegram ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='trainingtime',
            options={'verbose_name': 'Время начала тренировки', 'verbose_name_plural': 'Времена начала тренировки'},
        ),
        migrations.AlterModelOptions(
            name='trainingtopic',
            options={'verbose_name': 'Тема тренировки', 'verbose_name_plural': 'Темы тренировки'},
        ),
        migrations.AddField(
            model_name='training',
            name='max_participants',
            field=models.IntegerField(default=4, verbose_name='Кол-во участников'),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('open', 'Открыта для записи'), ('full', 'Мест нет (заполнена)'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='created', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='training',
            name='topics',
            field=models.ManyToManyField(to='trainy.trainingtopic', verbose_name='Темы тренировки'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_times',
            field=models.ManyToManyField(to='trainy.trainingtime', verbose_name='Времена начала тренировки'),
        ),
        migrations.AlterField(
            model_name='trainingtime',
            name='time',
            field=models.TimeField(unique=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='name',
            field=models.CharField(unique=True, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='TrainingReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.ManyToManyField(to='trainy.trainingtopic', verbose_name='Темы тренировки')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainy.training', verbose_name='Тренировка')),
                ('training_times', models.ManyToManyField(to='trainy.trainingtime', verbose_name='Времена начала тренировки')),
            ],
        ),
    ]
