# Generated by Django 5.2.4 on 2025-07-30 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0003_student_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='trainingreq',
            options={'verbose_name': 'Запрос на тренировку', 'verbose_name_plural': 'Запросы на тренировку'},
        ),
        migrations.AddField(
            model_name='trainingreq',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='trainy.student', verbose_name='Ученик'),
            preserve_default=False,
        ),
    ]
