# Generated by Django 5.2.4 on 2025-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0004_alter_student_options_alter_trainingreq_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingreq',
            name='training_times',
            field=models.ManyToManyField(to='trainy.trainingtime', verbose_name='Время начала тренировки'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingreq',
            unique_together={('student', 'training')},
        ),
    ]
