# Generated by Django 5.2.4 on 2025-07-30 21:32

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0005_alter_trainingreq_training_times_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingreq',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainingreq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now
            , verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
