# Generated by Django 5.2.4 on 2025-07-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0006_alter_trainingreq_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingreq',
            unique_together={('student', 'training')},
        ),
    ]
