# Generated by Django 5.2.4 on 2025-07-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0007_alter_trainingreq_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, to='trainy.student', verbose_name='Участники'),
        ),
    ]
