# Generated by Django 5.2.4 on 2025-07-31 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0008_training_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='final_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='final_time', to='trainy.trainingtime', verbose_name='Время начала тренировки'),
            preserve_default=False,
        ),
    ]
