# Generated by Django 5.2.4 on 2025-07-31 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0009_training_final_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='final_topic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='final_topic', to='trainy.trainingtopic', verbose_name='Тема тренировки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='final_time',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_time', to='trainy.trainingtime', verbose_name='Время начала тренировки'),
        ),
    ]
