# Generated by Django 5.2.4 on 2025-07-31 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0010_training_final_topic_alter_training_final_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='final_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_time', to='trainy.trainingtime', verbose_name='Время начала тренировки'),
        ),
        migrations.AlterField(
            model_name='training',
            name='final_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_topic', to='trainy.trainingtopic', verbose_name='Тема тренировки'),
        ),
        migrations.AlterField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='trainy.student', verbose_name='Участники'),
        ),
    ]
