# Generated by Django 5.2.4 on 2025-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0011_alter_training_final_time_alter_training_final_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tg_id',
            field=models.CharField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tg_name',
            field=models.CharField(unique=True, verbose_name='Ник telegram'),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя'),
        ),
    ]
