# Generated by Django 5.2.4 on 2025-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0012_student_notes_alter_student_name_alter_student_tg_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, to='trainy.student', verbose_name='Участники'),
        ),
    ]
