# Generated by Django 5.2.4 on 2025-08-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0013_alter_training_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tg_name',
            field=models.CharField(verbose_name='Ник telegram'),
        ),
    ]
