# Generated by Django 5.2.4 on 2026-01-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0014_alter_student_tg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tg_name',
            field=models.CharField(blank=True, null=True, verbose_name='Ник telegram'),
        ),
    ]
