# Generated by Django 5.2.10 on 2026-01-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0015_alter_student_tg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Имя')),
                ('address', models.CharField(unique=True, verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
