# Generated by Django 5.2.10 on 2026-01-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0016_trainingplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplace',
            name='address',
            field=models.CharField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
