# Generated by Django 5.2.10 on 2026-01-30 19:10

import django.db.models.deletion
from django.db import migrations, models

def create_default_trainingplace(apps, schema_editor):
    TrainingPlace = apps.get_model('trainy', 'TrainingPlace')
    
    TrainingPlace.objects.create(id=1, name='Default Place', latitude=0.0, longitude=0.0)

class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0017_alter_trainingplace_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='place', to='trainy.trainingplace', verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
