# Generated by Django 6.0.1 on 2026-02-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0018_training_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('open', 'Открыта для голосования'), ('full', 'Мест нет (заполнена)'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='created', verbose_name='Статус'),
        ),
    ]
